### ISSUE TITLE
安装后无法启动

### ISSUE THREAD

**Issue by hhy443482112** [jiangxufeng/v2rayL#13]
环境为ubuntu 19.04
Traceback (most recent call last):
  File "v2rayLui.py", line 20, in <module>
  File "/home/summer/.virtualenvs/v2rayL/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pyzbar/pyzbar.py", line 7, in <module>
  File "/home/summer/.virtualenvs/v2rayL/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pyzbar/wrapper.py", line 143, in <module>
  File "site-packages/pyzbar/wrapper.py", line 136, in zbar_function
  File "site-packages/pyzbar/wrapper.py", line 115, in load_libzbar
  File "site-packages/pyzbar/zbar_library.py", line 65, in load
ImportError: Unable to find zbar shared library
[1072] Failed to execute script v2rayLui

**Comment by jiangxufeng** [comment]
sudo apt-get install zbar-tools

安装脚本里面配置有安装zbar-tools的语句，在ubuntu18.04测试没有问题，您可以尝试在19.04运行上述命令尝试安装一下

**Comment by hhy443482112** [comment]
兼容不太OK，我还是手动改v2ray的config.json吧:)
