### ISSUE TITLE
各种错误，重新打包也不行

### ISSUE THREAD

**Issue by hao203** [jiangxufeng/v2rayL#139]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
4534 ERROR: Tcl/Tk improperly installed on this system.

**Comment by xtccc** [comment]
换python版本为3.6重新打包
