### ISSUE TITLE
centos8 运行完安装脚本就报错（尝试编译安装也不行）

### ISSUE THREAD

**Issue by ericdoomed** [jiangxufeng/v2rayL#140]
Traceback (most recent call last):
  File "v2rayLui.py", line 20, in <module>
  File "/home/summer/.virtualenvs/v2rayL/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pyzbar/pyzbar.py", line 7, in <module>
  File "/home/summer/.virtualenvs/v2rayL/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pyzbar/wrapper.py", line 143, in <module>
  File "site-packages/pyzbar/wrapper.py", line 136, in zbar_function
  File "site-packages/pyzbar/wrapper.py", line 115, in load_libzbar
  File "site-packages/pyzbar/zbar_library.py", line 65, in load
ImportError: Unable to find zbar shared library
[17117] Failed to execute script v2rayLui

**Comment by Zero1981** [comment]
红帽子系的系统恐怕不太行啊。作者在debian系+py3下开发的。
