### ISSUE TITLE
打包过程中断

### ISSUE THREAD

**Issue by GotTal** [jiangxufeng/v2rayL#202]
直击重点，提示如下：
63 INFO: checking PYZ
64 INFO: Building PYZ because PYZ-00.toc is non existent
64 INFO: Building PYZ (ZlibArchive) /root/v2rayL/v2rayL-GUI/build/v2rayLui/PYZ-00.pyz
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/root/v2rayL/v2rayL-GUI/v2rayLui.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/usr/local/lib/python3.8/dist-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)

**Comment by xtccc** [comment]
建议你用conda之类的把你的python版本切换一下，你这个是python3.8，打包要用python3.6

**Comment by GotTal** [comment]
好的我试试 谢谢哈
