### ISSUE TITLE
第三步打包不成功

### ISSUE THREAD

**Issue by FlyDre** [jiangxufeng/v2rayL#209]
FileNotFoundError: [Errno 2] No such file or directory: 'objcopy': 'objcopy'
请问这个问题怎么解决呢？

**Comment by FlyDre** [comment]
111962 INFO: Appending archive to ELF section in EXE /home/lyz/v2rayL/v2rayL/v2rayL-GUI/dist/v2rayLui
Traceback (most recent call last):
  File "/home/lyz/anaconda3/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/lyz/v2rayL/v2rayL/v2rayL-GUI/v2rayLui.spec", line 33, in <module>
    console=True , icon='images/logo.ico')
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 444, in __init__
    self.__postinit__()
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/building/api.py", line 603, in assemble
    self.name)
  File "/home/lyz/anaconda3/lib/python3.6/site-packages/PyInstaller/compat.py", line 566, in exec_command_all
    stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/home/lyz/anaconda3/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/lyz/anaconda3/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'objcopy': 'objcopy'
