### ISSUE TITLE
ubuntu20.04系统python3.8打包报错

### ISSUE THREAD

**Issue by zhgxn** [jiangxufeng/v2rayL#217]
27 INFO: PyInstaller: 3.5
27 INFO: Python: 3.8.5
37 INFO: Platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.29
37 INFO: wrote /home/jas/fanqiang/v2rayL-master/v2rayL-GUI/v2rayLui.spec
39 INFO: UPX is not available.
39 INFO: Extending PYTHONPATH with paths
['/home/jas/fanqiang/v2rayL-master/v2rayL-GUI',
 '/home/jas/fanqiang/v2rayL-master/v2rayL-GUI/config.py',
 '/home/jas/fanqiang/v2rayL-master/v2rayL-GUI/sub2conf_api.py',
 '/home/jas/fanqiang/v2rayL-master/v2rayL-GUI/v2rayL_api.py',
 '/home/jas/fanqiang/v2rayL-master/v2rayL-GUI/v2rayL_threads.py',
 '/home/jas/fanqiang/v2rayL-master/v2rayL-GUI/utils.py',
 '/home/jas/fanqiang/v2rayL-master/v2rayL-GUI']
40 INFO: checking Analysis
40 INFO: Building Analysis because Analysis-00.toc is non existent
40 INFO: Initializing module dependency graph...
42 INFO: Initializing module graph hooks...
42 INFO: Analyzing base_library.zip ...
1570 INFO: Processing pre-find module path hook   distutils
3102 INFO: running Analysis Analysis-00.toc
3128 INFO: Caching module hooks...
3130 INFO: Analyzing /home/jas/fanqiang/v2rayL-master/v2rayL-GUI/v2rayLui.py
3237 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
4256 INFO: Loading module hooks...
4256 INFO: Loading module hook "hook-PyQt5.py"...
4295 INFO: Loading module hook "hook-encodings.py"...
4326 INFO: Loading module hook "hook-PIL.Image.py"...
4501 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
4502 INFO: Import to be excluded not found: 'FixTk'
4502 INFO: Excluding import 'tkinter'
4502 INFO: Loading module hook "hook-pydoc.py"...
4502 INFO: Loading module hook "hook-certifi.py"...
4502 INFO: Loading module hook "hook-xml.py"...
4529 INFO: Loading module hook "hook-lib2to3.py"...
4531 INFO: Loading module hook "hook-PIL.py"...
4532 INFO: Import to be excluded not found: 'FixTk'
4532 INFO: Excluding import 'PySide'
4533 INFO:   Removing import of PySide from module PIL.ImageQt
4533 INFO: Excluding import 'PyQt5'
4534 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
4534 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
4535 INFO: Excluding import 'PyQt4'
4535 INFO:   Removing import of PyQt4 from module PIL.ImageQt
4536 INFO: Excluding import 'tkinter'
4537 INFO:   Removing import of tkinter from module PIL.ImageTk
4537 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
4554 INFO: Loading module hook "hook-distutils.py"...
4556 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
4556 INFO: Loading module hook "hook-qtawesome.py"...
4557 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
4593 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
4660 INFO: Loading module hook "hook-sysconfig.py"...
4681 INFO: Looking for ctypes DLLs
4711 INFO: Analyzing run-time hooks ...
4714 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
4716 INFO: Including run-time hook 'pyi_rth_pyqt5.py'
4717 INFO: Including run-time hook 'pyi_rth_certifi.py'
4724 INFO: Looking for dynamic libraries
7353 INFO: Looking for eggs
7354 INFO: Python library not in binary dependencies. Doing additional searching...
7438 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
7444 INFO: Warnings written to /home/jas/fanqiang/v2rayL-master/v2rayL-GUI/build/v2rayLui/warn-v2rayLui.txt
7473 INFO: Graph cross-reference written to /home/jas/fanqiang/v2rayL-master/v2rayL-GUI/build/v2rayLui/xref-v2rayLui.html
7487 INFO: checking PYZ
7488 INFO: Building PYZ because PYZ-00.toc is non existent
7488 INFO: Building PYZ (ZlibArchive) /home/jas/fanqiang/v2rayL-master/v2rayL-GUI/build/v2rayLui/PYZ-00.pyz
Traceback (most recent call last):
  File "/home/jas/fanqiang/v2rayL-master/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/jas/fanqiang/v2rayL-master/v2rayL-GUI/v2rayLui.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/home/jas/fanqiang/v2rayL-master/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)

**Comment by atzlinux** [comment]
可以试一下直接打好 deb 包，是否可以直接使用？

**Comment by sangshuduo** [comment]
me2

**Comment by TaojingZHANG** [comment]
试着更新一下 pyinstaller：pip install --upgrade pyinstaller

**Comment by ChiLincoln** [comment]
> 试着更新一下 pyinstaller：pip install --upgrade pyinstaller

so nice ! so nice!真不戳!真不戳!
