### ISSUE TITLE
ubuntu下载之后打不开

### ISSUE THREAD

**Issue by HRC0401** [jiangxufeng/v2rayL#39]

**Comment by HRC0401** [comment]
Ubuntu 18.04

**Comment by jiangxufeng** [comment]
你好，你可以查看一下在终端运行` /usr/bin/v2rayL/v2rayLui`
看一下出了什么错误

**Comment by 467057463** [comment]
$ /usr/bin/v2rayL/v2rayLui
[5387] Cannot open self /usr/bin/v2rayL/v2rayLui or archive /usr/bin/v2rayL/v2rayLui.pkg

**Comment by iambupu** [comment]
ubuntu 18.04也是同样的错误

**Comment by JianyueZ** [comment]
> > Ubuntu 18.04
> 
> 你好，你可以查看一下在终端运行` /usr/bin/v2rayL/v2rayLui`
> 看一下出了什么错误

`jerry@LAPTOP-V78A3VRT:~$ /usr/bin/v2rayL/v2rayLui
Traceback (most recent call last):
  File "utils.py", line 74, in qt_message_handler
ValueError: not enough values to unpack (expected 2, got 1)
Aborted
jerry@LAPTOP-V78A3VRT:~$`

您好！这是WSL 2 的 Debian 的结果。也是安装后v2rayL打不开，没有反应。

**Comment by jiangxufeng** [comment]
@JianyueZ 你这个问题可以参考一下[#53](https://github.com/jiangxufeng/v2rayL/issues/53),

**Comment by hjklyuio** [comment]
> > Ubuntu 18.04
> 
> 你好，你可以查看一下在终端运行` /usr/bin/v2rayL/v2rayLui`
> 看一下出了什么错误
Traceback (most recent call last):
  File "utils.py", line 74, in qt_message_handler
ValueError: not enough values to unpack (expected 2, got 1)
Aborted (core dumped)

**Comment by JianyueZ** [comment]
> @JianyueZ 你这个问题可以参考一下[#53](https://github.com/jiangxufeng/v2rayL/issues/53),

谢谢！不用sudo重新安装没有再出现这个错误。但是出现了另一个错误，不是很懂，请教一下：
 [10631] Error loading Python lib '/tmp/_MEI9Jh13R/libpython3.6m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI9Jh13R/libpython3.6m.so.1.0)
