### ISSUE TITLE
can't open v2rayl

### ISSUE THREAD

**Issue by hjklyuio** [jiangxufeng/v2rayL#73]
when I run '/usr/bin/v2rayL/v2rayLui' in terminal:
Traceback (most recent call last):
  File "utils.py", line 74, in qt_message_handler
ValueError: not enough values to unpack (expected 2, got 1)
Aborted (core dumped)

**Comment by jiangxufeng** [comment]
这是安装时出现了权限问题，你可以看一下这个[#53](https://github.com/jiangxufeng/v2rayL/issues/53)

**Comment by ecstayalive** [comment]
请问有时候打不开v2rayL，报错是File "utils.py", line 74, in qt_message_handler
ValueError: not enough values to unpack (expected 2, got 1)
但有时候又可以正常打开，是怎么会事
