### ISSUE TITLE
Failed to execute script v2rayLui

### ISSUE THREAD

**Issue by xgdgsc** [jiangxufeng/v2rayL#78]
```
Traceback (most recent call last):
  File "v2rayLui.py", line 775, in <module>
  File "v2rayLui.py", line 100, in __init__
AttributeError: 'CurrentStatus' object has no attribute 'proxy'
[1331] Failed to execute script v2rayLui
```

没动就突然打不开了

**Comment by xgdgsc** [comment]
卸载重装后可以，为什么设置没有保存。这软件就不能搞个不需要sudo的版本吗
